"""initial schema

Revision ID: d23d407245e2
Revises: 
Create Date: 2026-08-05 22:51:15.294664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23d407245e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('reading_time', sa.Time(), nullable=False),
    sa.Column('recorded_by', sa.String(length=100), nullable=False),
    sa.Column('wing_a', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('wing_b', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('wing_c', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('wing_a >= 0', name='ck_meter_wing_a_nonneg'),
    sa.CheckConstraint('wing_b >= 0', name='ck_meter_wing_b_nonneg'),
    sa.CheckConstraint('wing_c >= 0', name='ck_meter_wing_c_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_at', name='uq_meter_created_at')
    )
    op.create_table('staff',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('security','technical','manager','gym_attendant')", name='ck_staff_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tank_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('reading_time', sa.Time(), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=False),
    sa.Column('ug_domestic_ab', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ug_domestic_c', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ug_flushing_ab', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ug_flushing_c', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fire_tank', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('oh_dom_a', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('oh_dom_b', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('oh_dom_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('oh_flush_a', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('oh_flush_b', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('oh_flush_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("session IN ('Morning','Afternoon','Night')", name='ck_tank_session'),
    sa.CheckConstraint('fire_tank BETWEEN 0 AND 100', name='ck_tank_fire_pct'),
    sa.CheckConstraint('oh_dom_a BETWEEN 0 AND 100', name='ck_tank_oh_dom_a_pct'),
    sa.CheckConstraint('oh_dom_b BETWEEN 0 AND 100', name='ck_tank_oh_dom_b_pct'),
    sa.CheckConstraint('oh_dom_c BETWEEN 0 AND 100', name='ck_tank_oh_dom_c_pct'),
    sa.CheckConstraint('oh_flush_a BETWEEN 0 AND 100', name='ck_tank_oh_flush_a_pct'),
    sa.CheckConstraint('oh_flush_b BETWEEN 0 AND 100', name='ck_tank_oh_flush_b_pct'),
    sa.CheckConstraint('oh_flush_c BETWEEN 0 AND 100', name='ck_tank_oh_flush_c_pct'),
    sa.CheckConstraint('ug_domestic_ab >= 0', name='ck_tank_ug_dom_ab_nonneg'),
    sa.CheckConstraint('ug_domestic_c >= 0', name='ck_tank_ug_dom_c_nonneg'),
    sa.CheckConstraint('ug_flushing_ab >= 0', name='ck_tank_ug_flush_ab_nonneg'),
    sa.CheckConstraint('ug_flushing_c >= 0', name='ck_tank_ug_flush_c_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_at', name='uq_tank_created_at')
    )
    op.create_table('wings',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('shift', sa.String(length=10), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('in','out')", name='ck_attendance_event_type'),
    sa.CheckConstraint("shift IN ('day','night') OR shift IS NULL", name='ck_attendance_shift'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'occurred_at', name='uq_attendance_staff_time')
    )
    op.create_index('ix_attendance_event_date', 'attendance', ['event_date'], unique=False)
    op.create_index('ix_attendance_staff_event_date', 'attendance', ['staff_id', 'event_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_staff_event_date', table_name='attendance')
    op.drop_index('ix_attendance_event_date', table_name='attendance')
    op.drop_table('attendance')
    op.drop_table('wings')
    op.drop_table('tank_status')
    op.drop_table('staff')
    op.drop_table('meter_readings')
    op.drop_table('app_config')
    # ### end Alembic commands ###
